#!/bin/bash

echo "Hello, lamer :) Let's do some things :)"

read -p 'Login: ' login
read -p 'IP ' ip
read -p 'Port ' port

ssh -4 -fND 1080 $login@$ip -p $port
router --ap wlx1cbfce156098 _boris_ -o lo --tp 1234 --dns $1 --daemon
gost -L redirect://:1234 -F socks://:1080 -D &
