#!/bin/bash

echo "Hello, lamer :) Let's do some things :)"

read -p 'Login: ' login
read -p 'IP ' ip
read -p 'Port ' port
read -p '[wlan] adapter ' adapter
ssh -4 -fND 1080 $login@$ip -p $port
lnxrouter --ap $adapter _boris_ --tp 1234 --dns $1 --daemon
gost -L redirect://:1234 -F socks://:1080 -D &
