#!/bin/sh

#Wipe cache and other

        sync; echo 3 > /proc/sys/vm/drop_caches
        swapoff -a && swapon -a
        sleep 1

  killall -q telegram-desktop chrome dropbox iceweasel skype icedove thunderbird firefox-esr firefox chromium xchat transmission kvirc pidgin hexchat # feel free to add your own internet connected app
sleep 1
  bleachbit -c telegram-desktop.cache adobe_reader.cache chromium.cache chromium.current_session chromium.history elinks.history emesene.cache epiphany.cache firefox.url_history flash.cache flash.cookies google_chrome.cache goog$
sleep 1

#reinstall services

sudo apt-get reinstall openresolv -y && sudo apt-get reinstall network-manager -y
su x -c 'notify-send "resolvconf и networkmanager переустановлены..."'
sleep 1

#add some text :)
echo "[connection]" >> /etc/NetworkManager/NetworkManager.conf
echo "ethernet.cloned-mac-address=preserve" >> /etc/NetworkManager/NetworkManager.conf
echo "wifi.cloned-mac-address=preserve" >> /etc/NetworkManager/NetworkManager.conf
sleep 1

#change mac
ifconfig eth0 down
ifconfig wlan0 down
ifconfig wlan1 down
/usr/bin/macchanger -A eth0
/usr/bin/macchanger -A wlan0
/usr/bin/macchanger -A wlan1
ifconfig eth0 up
ifconfig wlan0 up
ifconfig wlan1 up
service network-manager restart
sleep 1

su x -c 'notify-send "wlan0 wlan1 eth0 mac-адреса успешно изменены..."'
sleep 10

#wireguard start
wg-quick up azirevpn-se1	

su x -c 'notify-send "wireguard запущен...готово!"'


exit 0
