#!/bin/sh

#for LIVE system, comment if not

#sudo apt-get purge resolvconf && sudo service network-manager restart
#sudo apt reinstall resolvconf


#Wipe cache and other

        sync; echo 3 > /proc/sys/vm/drop_caches
        swapoff -a && swapon -a
        sleep 1

  killall -q chrome dropbox iceweasel skype icedove thunderbird firefox-esr firefox chromium xchat transmission kvirc pidgin hexchat # feel free to add your own internet connected app
sleep 1
  bleachbit -c adobe_reader.cache chromium.cache chromium.current_session chromium.history elinks.history emesene.cache epiphany.cache firefox.url_history flash.cache flash.cookies google_chrome.cache goog$
sleep 1

#reinstall resolvconf and network-manager
sudo apt-get reinstall resolvconf -y && sudo apt-get reinstall network-manager -y
su x -c 'notify-send "resolvconf и networkmanager переустановлены..."'
sleep 1

#randomize mac
echo "[connection]" >> /etc/NetworkManager/NetworkManager.conf
echo "ethernet.cloned-mac-address=preserve" >> /etc/NetworkManager/NetworkManager.conf
echo "wifi.cloned-mac-address=preserve" >> /etc/NetworkManager/NetworkManager.conf
sleep 1

ifconfig eth0 down
ifconfig wlan0 down
ifconfig wlan1 down
/usr/bin/macchanger -A eth0
/usr/bin/macchanger -A wlan0
/usr/bin/macchanger -A wlan1
ifconfig eth0 up
ifconfig wlan0 up
ifconfig wlan1 up
service network-manager restart
sleep 1

su x -c 'notify-send "wlan0 wlan1 eth0 mac-адреса успешно изменены..."'
sleep 10

wg-quick up azirevpn-se1
su x -c 'notify-send "wireguard запущен...готово!"'


exit 0
